import * as THREE from 'three';
export type Difficulty='Beginner'|'Amateur'|'Semi-Pro'|'Professional'|'World Class'|'Legendary';
export type FormationName='4-3-3'|'4-4-2'|'4-2-3-1'|'3-5-2'|'5-3-2';
type P={team:number;n:number;name:string;role:string;ovr:number;pos:THREE.Vector3;vel:THREE.Vector3;mesh:THREE.Group;ball:boolean;stamina:number};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const FORM:Record<FormationName,number[][]>={'4-3-3':[[-47,0],[-35,-24],[-35,24],[-12,-30],[-12,30],[0,-14],[0,14],[15,-32],[22,0],[15,32]],'4-4-2':[[-47,0],[-35,-25],[-35,25],[-10,-31],[-10,31],[0,-30],[0,30],[0,0],[24,-16],[24,16]],'4-2-3-1':[[-47,0],[-35,-25],[-35,25],[-10,-31],[-10,31],[-2,-15],[-2,15],[14,-30],[18,0],[14,30]],'3-5-2':[[-33,-25],[-33,25],[-20,0],[-5,-32],[-5,-12],[-5,12],[-5,32],[13,-20],[25,-11],[25,11]],'5-3-2':[[-38,-28],[-38,-10],[-38,10],[-38,28],[-5,-18],[-5,18],[5,0],[20,-15],[28,-11],[28,11]]};
export class FootballGame{
 private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(48,1,.1,220);private renderer:THREE.WebGLRenderer;private ball!:THREE.Mesh;private bv=new THREE.Vector3();private players:P[]=[];private controlled!:P;private keys=new Set<string>();private raf=0;private last=performance.now();private rt=0;private match=0;private half=1;private score=[0,0];private event='KICK OFF';private cooldown=0;private switchCooldown=0;private goalCooldown=0;private listeners=new Set<(s:any)=>void>();private ro:ResizeObserver;private form:FormationName;private diff:Difficulty;private targetCam=new THREE.Vector3();private ref!:THREE.Group;private arrows:THREE.Mesh[]=[];private flash!:HTMLDivElement;
 constructor(private host:HTMLElement,d:Difficulty='Amateur',f:FormationName='4-3-3'){this.diff=d;this.form=f;this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.innerHTML='';host.style.position='relative';host.appendChild(this.renderer.domElement);this.flash=document.createElement('div');Object.assign(this.flash.style,{position:'absolute',inset:'0',pointerEvents:'none',opacity:'0',background:'radial-gradient(circle,rgba(255,255,255,.9),transparent 65%)',transition:'opacity .12s'});host.appendChild(this.flash);this.world();this.spawn();this.kickoff(0);this.ro=new ResizeObserver(()=>this.resize());this.ro.observe(host);this.resize();addEventListener('keydown',this.down);addEventListener('keyup',this.up);this.raf=requestAnimationFrame(this.loop)}
 onState(fn:(s:any)=>void){this.listeners.add(fn);fn(this.state());return()=>this.listeners.delete(fn)}
 private emit(){const s=this.state();this.listeners.forEach(f=>f(s))}
 private state(){const m=Math.floor(this.match);return{score:[...this.score],time:`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,half:this.half,player:this.controlled?.name||'',stamina:Math.round(this.controlled?.stamina||100),event:this.event,shots:[0,0],shotsOn:[0,0],passes:[0,0],completed:[0,0],poss:[50,50]}}
 private world(){this.scene.background=new THREE.Color(0x071018);this.scene.add(new THREE.HemisphereLight(0xdff7ff,0x08120c,2.4));const sun=new THREE.DirectionalLight(0xffffff,4);sun.position.set(-30,65,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-70;sun.shadow.camera.right=70;sun.shadow.camera.top=50;sun.shadow.camera.bottom=-50;this.scene.add(sun);const grass=new THREE.Mesh(new THREE.PlaneGeometry(105,68),new THREE.MeshStandardMaterial({color:0x17663f,roughness:.9}));grass.rotation.x=-Math.PI/2;grass.receiveShadow=true;this.scene.add(grass);for(let x=-52.5;x<52.5;x+=7){const s=new THREE.Mesh(new THREE.PlaneGeometry(7,68),new THREE.MeshBasicMaterial({color:0x1e7147,transparent:true,opacity:.3}));s.rotation.x=-Math.PI/2;s.position.set(x,.01,0);this.scene.add(s)}const lm=new THREE.LineBasicMaterial({color:0xffffff});const line=(a:number[][])=>{const g=new THREE.BufferGeometry().setFromPoints(a.map(v=>new THREE.Vector3(v[0],.035,v[1])));this.scene.add(new THREE.Line(g,lm))};line([[-52.5,-34],[52.5,-34],[52.5,34],[-52.5,34],[-52.5,-34]]);line([[0,-34],[0,34]]);const c=new THREE.EllipseCurve(0,0,9.15,9.15,0,Math.PI*2);line(c.getPoints(80).map(p=>[p.x,p.y]));line([[-52.5,-20.15],[-36.5,-20.15],[-36.5,20.15],[-52.5,20.15],[-52.5,-20.15]]);line([[52.5,-20.15],[36.5,-20.15],[36.5,20.15],[52.5,20.15],[52.5,-20.15]]);line([[-52.5,-9.16],[-43.35,-9.16],[-43.35,9.16],[-52.5,9.16]]);line([[52.5,-9.16],[43.35,-9.16],[43.35,9.16],[52.5,9.16]]);this.goals();this.stadium();this.makeRef();this.makeArrows();this.ball=new THREE.Mesh(new THREE.SphereGeometry(.9,24,16),new THREE.MeshStandardMaterial({color:0xf5f5f5,roughness:.28}));this.ball.castShadow=true;this.scene.add(this.ball);this.camera.position.set(0,64,66);this.camera.lookAt(0,0,0)}
 private goals(){for(const x of[-52.5,52.5]){const m=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.4});for(const z of[-7.32,7.32]){const p=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,5.5,12),m);p.position.set(x,2.75,z);p.castShadow=true;this.scene.add(p)}const b=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,14.64,12),m);b.rotation.x=Math.PI/2;b.position.set(x,5.5,0);this.scene.add(b);const n=new THREE.Mesh(new THREE.BoxGeometry(6,5.2,14.4),new THREE.MeshStandardMaterial({color:0xffffff,transparent:true,opacity:.12,wireframe:true}));n.position.set(x+(x>0?3:-3),2.7,0);this.scene.add(n)}}
 private stadium(){const sm=new THREE.MeshStandardMaterial({color:0x202733,roughness:.8});for(const z of[-45,45]){const stand=new THREE.Mesh(new THREE.BoxGeometry(130,9,16),sm);stand.position.set(0,4.5,z);this.scene.add(stand);for(let i=0;i<75;i++){const c=new THREE.Mesh(new THREE.SphereGeometry(.55,6,5),new THREE.MeshStandardMaterial({color:i%3===0?0xffd35a:i%3===1?0x4da3ff:0xffffff}));c.position.set(-48+(i%25)*4,9+Math.floor(i/25)*1.5,z+(z>0?-5:5));this.scene.add(c)}}for(const x of[-66,66]){const stand=new THREE.Mesh(new THREE.BoxGeometry(14,9,105),sm);stand.position.set(x,4.5,0);this.scene.add(stand)}}
 private makeRef(){const g=new THREE.Group();const kit=new THREE.MeshStandardMaterial({color:0x111318});const skin=new THREE.MeshStandardMaterial({color:0xc98a6d});const body=new THREE.Mesh(new THREE.CapsuleGeometry(1.15,2.5,6,10),kit);body.position.y=3;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),skin);head.position.y=6;g.add(head);g.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});this.scene.add(g);this.ref=g}
 private makeArrows(){for(let i=0;i<3;i++){const a=new THREE.Mesh(new THREE.ConeGeometry(.8,3,4),new THREE.MeshBasicMaterial({color:0xffe04b,transparent:true,opacity:.9}));a.rotation.z=-Math.PI/2;a.position.y=2.4;this.scene.add(a);this.arrows.push(a)}}
 private spawn(){for(let t=0;t<2;t++){this.players.push(this.make(t,0,t?'RED GK':'BLUE GK','GK',80));for(let i=0;i<10;i++)this.players.push(this.make(t,i+1,`${t?'RED':'BLUE'} ${i+1}`,i<4?'DEF':i<7?'MID':'ATT',70+(i%6)*5))}this.controlled=this.players.find(p=>p.team===0&&p.role==='ATT')!}
 private make(team:number,n:number,name:string,role:string,ovr:number){const g=new THREE.Group();const kit=new THREE.MeshStandardMaterial({color:team?0xd82f48:0x197dff,roughness:.6});const skin=new THREE.MeshStandardMaterial({color:0xc98a6d});const dark=new THREE.MeshStandardMaterial({color:0x11151a});const torso=new THREE.Mesh(new THREE.CapsuleGeometry(1.15,2.3,7,12),kit);torso.position.y=3.1;g.add(torso);const shorts=new THREE.Mesh(new THREE.BoxGeometry(2,1,1.6),kit);shorts.position.y=1.55;g.add(shorts);const head=new THREE.Mesh(new THREE.SphereGeometry(1.02,16,12),skin);head.position.y=6.25;g.add(head);const hair=new THREE.Mesh(new THREE.SphereGeometry(1.04,16,8,0,Math.PI*2,0,Math.PI/2),dark);hair.position.y=6.55;g.add(hair);for(const x of[-.58,.58]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.38,2.1,6,8),dark);leg.position.set(x,.45,0);g.add(leg);const boot=new THREE.Mesh(new THREE.BoxGeometry(.65,.35,1.45),dark);boot.position.set(x,-.75,.35);g.add(boot)}for(const x of[-1.5,1.5]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.3,1.7,6,8),kit);arm.position.set(x,3.2,0);g.add(arm)}g.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});this.scene.add(g);return{team,n,name,role,ovr,pos:new THREE.Vector3(),vel:new THREE.Vector3(),mesh:g,ball:false,stamina:100}}
 private kickoff(team:number){this.ball.position.set(0,.9,0);this.bv.set(0,0,0);const spots=FORM[this.form];for(const p of this.players){p.ball=false;if(p.n===0)p.pos.set(p.team?49:-49,0,0);else{const s=spots[p.n-1];p.pos.set((p.team?1:-1)*s[0],0,s[1])}p.mesh.position.copy(p.pos);p.vel.set(0,0,0)}const k=this.players.find(p=>p.team===team&&p.role==='ATT')!;k.ball=true;this.controlled=this.players.find(p=>p.team===0&&p.role==='ATT')!;this.goalCooldown=1;this.event='KICK OFF'}
 private down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase(),map:Record<string,string>={arrowup:'w',arrowdown:'s',arrowleft:'a',arrowright:'d'};if([' ','j','k','l','i','o','p','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();this.keys.add(map[k]||k)};private up=(e:KeyboardEvent)=>{const k=e.key.toLowerCase(),map:Record<string,string>={arrowup:'w',arrowdown:'s',arrowleft:'a',arrowright:'d'};this.keys.delete(map[k]||k)};
 private loop=(n:number)=>{const dt=clamp((n-this.last)/1000,0,.033);this.last=n;this.rt+=dt;this.update(dt);this.renderer.render(this.scene,this.camera);this.raf=requestAnimationFrame(this.loop)}
 private update(dt:number){this.cooldown=Math.max(0,this.cooldown-dt);this.switchCooldown=Math.max(0,this.switchCooldown-dt);this.goalCooldown=Math.max(0,this.goalCooldown-dt);if(this.match<90*60){this.match+=dt*15;if(this.match>=45*60&&this.half===1){this.half=2;this.event='HALF TIME';this.kickoff(1)}}else{this.event='FULL TIME';return}this.user(dt);this.ai(dt);this.ballPhysics(dt);this.possession();this.cameraFollow(dt);this.refFollow(dt);this.arrowsFollow();if(Math.floor(this.rt*5)%2===0)this.emit()}
 private user(dt:number){const p=this.controlled;let x=(this.keys.has('d')?1:0)-(this.keys.has('a')?1:0),z=(this.keys.has('s')?1:0)-(this.keys.has('w')?1:0);const d=new THREE.Vector3(x,0,z);if(d.lengthSq())d.normalize();const sprint=this.keys.has('shift')&&p.stamina>2;const speed=(6.2+p.ovr*.045)*(sprint?1.45:1);p.vel.lerp(d.multiplyScalar(speed),1-Math.exp(-12*dt));p.pos.addScaledVector(p.vel,dt);p.pos.x=clamp(p.pos.x,-51,51);p.pos.z=clamp(p.pos.z,-32.5,32.5);p.stamina=clamp(p.stamina+(sprint?-13:6)*dt,0,100);p.mesh.position.copy(p.pos);if(p.ball)this.ball.position.copy(p.pos).setY(.9);if(this.keys.has(' ')&&this.switchCooldown<=0){this.switchCooldown=.25;this.switchPlayer()}if(this.keys.has('j'))this.pass();if(this.keys.has('k'))this.pass(true);if(this.keys.has('l'))this.shoot();if(this.keys.has('p'))this.shoot(true);if(this.keys.has('o'))this.tackle()}
 private switchPlayer(){const target=this.players.filter(p=>p.team===0).sort((a,b)=>a.pos.distanceTo(this.ball.position)-b.pos.distanceTo(this.ball.position))[0];if(!target)return;this.controlled=target;this.event=`CONTROL: ${target.name}`}
 private pass(through=false){const p=this.controlled;if(this.cooldown>0||!p.ball)return;this.cooldown=.3;const mates=this.players.filter(q=>q.team===p.team&&q!==p).sort((a,b)=>a.pos.distanceTo(p.pos)-b.pos.distanceTo(p.pos));const r=mates.find(q=>q.role==='ATT'||q.role==='MID')||mates[0];if(!r)return;const d=r.pos.clone().sub(p.pos);d.y=0;d.normalize();p.ball=false;this.ball.position.copy(p.pos).setY(.9);this.bv.copy(d).multiplyScalar(through?21:17);this.bv.y=through?1:0;this.event=through?'THROUGH BALL':'PASS'}
 private shoot(chip=false){const p=this.controlled;if(this.cooldown>0||!p.ball)return;this.cooldown=.5;p.ball=false;const gx=p.team?-52.5:52.5;const goal=new THREE.Vector3(gx,.9,(Math.random()-.5)*11);const d=goal.sub(p.pos);d.y=0;d.normalize();this.ball.position.copy(p.pos).setY(.9);this.bv.copy(d).multiplyScalar(22);this.bv.y=chip?10:3;this.event=chip?'CHIP SHOT':'SHOT'}
 private tackle(){const p=this.controlled;if(this.cooldown>0)return;this.cooldown=.35;const e=this.players.filter(q=>q.team!==p.team).sort((a,b)=>a.pos.distanceTo(p.pos)-b.pos.distanceTo(p.pos))[0];if(e&&e.pos.distanceTo(p.pos)<4&&Math.random()<p.ovr/105){this.players.forEach(q=>q.ball=false);p.ball=true;this.ball.position.copy(p.pos).setY(.9);this.event='TACKLE'}}
 private ai(dt:number){const holder=this.players.find(p=>p.ball);const ballTeam=holder?.team??-1;for(const p of this.players){if(p===this.controlled)continue;const mates=this.players.filter(q=>q.team===p.team);const nearest=mates.slice().sort((a,b)=>a.pos.distanceTo(this.ball.position)-b.pos.distanceTo(this.ball.position))[0];let target=new THREE.Vector3();if(p.ball){const goalX=p.team?-45:45;target.set(goalX,0,clamp(this.ball.position.z,-24,24));if(Math.abs(p.pos.x-goalX)<10&&this.cooldown<=0&&Math.random()<dt*.55){p.ball=false;this.ball.position.copy(p.pos).setY(.9);const g=new THREE.Vector3(p.team?-52.5:52.5,.9,(Math.random()-.5)*10);const d=g.sub(p.pos);d.y=0;d.normalize();this.bv.copy(d).multiplyScalar(21);this.bv.y=3;this.event='AI SHOT'}}else if(ballTeam!==p.team&&nearest===p){target.copy(this.ball.position);const lead=this.bv.clone().multiplyScalar(.18);target.add(lead)}else if(ballTeam===p.team){const s=FORM[this.form][Math.max(0,p.n-1)]||[0,0];target.set((p.team?1:-1)*s[0],0,s[1]);target.x+=(this.ball.position.x-target.x)*.2;target.z+=(this.ball.position.z-target.z)*.15}else{const enemy=this.players.filter(q=>q.team!==p.team).sort((a,b)=>a.pos.distanceTo(p.pos)-b.pos.distanceTo(p.pos))[0];target.copy(enemy?.pos||this.ball.position);target.lerp(this.ball.position,.2)}if(p.role==='GK'){target.x=p.team?49:-49;target.z=clamp(this.ball.position.z,-9,9)}const d=target.sub(p.pos);if(d.lengthSq()>1){d.normalize();const speed=(5.6+p.ovr*.03)*(p.role==='GK'?.9:1);p.vel.lerp(d.multiplyScalar(speed),1-Math.exp(-8*dt));p.pos.addScaledVector(p.vel,dt)}else p.vel.multiplyScalar(.8);p.pos.x=clamp(p.pos.x,-51,51);p.pos.z=clamp(p.pos.z,-32.5,32.5);p.mesh.position.copy(p.pos);p.stamina=clamp(p.stamina+3*dt,0,100);if(!p.ball&&p.pos.distanceTo(this.ball.position)<2.2&&this.bv.length()<10)this.intercept(p)}}
 private intercept(p:P){const h=this.players.find(q=>q.ball);if(h&&h.team!==p.team){this.players.forEach(q=>q.ball=false);p.ball=true;if(p.team===0)this.controlled=p;this.event=`INTERCEPTION: ${p.name}`}else if(!h){this.players.forEach(q=>q.ball=false);p.ball=true;if(p.team===0)this.controlled=p;this.event=`RECOVERY: ${p.name}`}}
 private possession(){if(this.players.some(p=>p.ball))return;const p=this.players.slice().sort((a,b)=>a.pos.distanceTo(this.ball.position)-b.pos.distanceTo(this.ball.position))[0];if(p&&p.pos.distanceTo(this.ball.position)<2.3&&this.bv.length()<6){p.ball=true;if(p.team===0)this.controlled=p;this.event=`POSSESSION: ${p.name}`}}
 private ballPhysics(dt:number){if(this.players.some(p=>p.ball)){const h=this.players.find(p=>p.ball)!;this.ball.position.copy(h.pos).setY(.9);return}if(this.bv.lengthSq()===0)return;this.ball.position.addScaledVector(this.bv,dt);this.bv.multiplyScalar(Math.pow(.992,dt*60));this.bv.y-=22*dt;this.ball.position.y+=this.bv.y*dt;if(this.ball.position.y<.9){this.ball.position.y=.9;this.bv.y*=-.38;if(Math.abs(this.bv.y)<.35)this.bv.y=0}if(Math.abs(this.ball.position.z)>34){this.ball.position.z=clamp(this.ball.position.z,-34,34);this.bv.z*=-.8}if(this.ball.position.x>52.5||this.ball.position.x<-52.5){const inside=Math.abs(this.ball.position.z)<=7.32;if(inside&&this.goalCooldown<=0){const scoring=this.ball.position.x>0?0:1;this.score[scoring]++;this.event='GOAL!';this.goalCooldown=2;this.flash.style.opacity='1';setTimeout(()=>this.flash.style.opacity='0',250);this.bv.set(0,0,0);this.players.forEach(p=>p.ball=false);this.kickoff(1-scoring)}else{this.ball.position.x=clamp(this.ball.position.x,-52.4,52.4);this.bv.x*=-.7}}this.ball.rotation.x+=this.bv.z*dt*.2;this.ball.rotation.z-=this.bv.x*dt*.2}
 private cameraFollow(dt:number){const h=this.players.find(p=>p.ball);const f=h?h.pos:this.ball.position;this.targetCam.lerp(new THREE.Vector3(f.x,0,f.z),1-Math.exp(-4*dt));this.camera.position.lerp(new THREE.Vector3(this.targetCam.x,66,this.targetCam.z+66),1-Math.exp(-3*dt));this.camera.lookAt(this.targetCam.x,0,this.targetCam.z)}
 private refFollow(dt:number){const h=this.players.find(p=>p.ball);const f=h?h.pos:this.ball.position;this.ref.position.lerp(new THREE.Vector3(clamp(f.x+((h?.team===0)?3:-3),-47,47),0,clamp(f.z,-29,29)),1-Math.exp(-5*dt))}
 private arrowsFollow(){const p=this.controlled;if(!p)return;const t=p.ball?this.ball.position:this.players.filter(q=>q.team===p.team).sort((a,b)=>a.pos.distanceTo(this.ball.position)-b.pos.distanceTo(this.ball.position))[0]?.pos;if(!t)return;const d=t.clone().sub(p.pos);d.y=0;if(d.lengthSq()<.1)return;d.normalize();for(let i=0;i<this.arrows.length;i++){const a=this.arrows[i];a.position.copy(p.pos).addScaledVector(d,4+i*3);a.position.y=2.2;a.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(d.x,.25,d.z))}}
 private resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
 destroy(){cancelAnimationFrame(this.raf);this.ro.disconnect();removeEventListener('keydown',this.down);removeEventListener('keyup',this.up);this.renderer.dispose();this.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose()}});this.renderer.domElement.remove();this.flash.remove()}
}
