import * as THREE from 'three';

export type Difficulty = 'Beginner'|'Amateur'|'Semi-Pro'|'Professional'|'World Class'|'Legendary';
export type FormationName = '4-3-3'|'4-4-2'|'4-2-3-1'|'3-5-2'|'5-3-2';

type Stats={pace:number;shooting:number;passing:number;dribbling:number;defending:number;physical:number;stamina:number;reactions:number};
type Player={id:number;team:0|1;name:string;number:number;role:string;stats:Stats;pos:THREE.Vector3;vel:THREE.Vector3;mesh:THREE.Group;hasBall:boolean;stamina:number;yellow:number;red:boolean;target:THREE.Vector3};

const FORMATIONS:Record<FormationName,[number,number,number][]>={
 '4-3-3':[[0,-5.2],[1,-3.6],[-1,-3.6],[2,-1.4],[-2,-1.4],[0,-1.0],[3,.9],[0,1.8],[-3,.9]],
 '4-4-2':[[0,-5.2],[-2,-3.5],[2,-3.5],[-3,-1.0],[3,-1.0],[-2,1.0],[2,1.0],[0,1.2],[-1.8,3.0],[1.8,3.0]],
 '4-2-3-1':[[0,-5.2],[-2,-3.5],[2,-3.5],[-3,-1.0],[3,-1.0],[-1.7,.4],[1.7,.4],[-2.7,1.8],[0,2.2],[2.7,1.8]],
 '3-5-2':[[0,-5.2],[-2.5,-3.2],[2.5,-3.2],[0,-3.4],[-3,0],[-1.4,.7],[0,0],[1.4,.7],[3,0],[-1.5,3.0],[1.5,3.0]],
 '5-3-2':[[0,-5.2],[-3.2,-3.5],[0,-3.8],[3.2,-3.5],[-4,.2],[4,.2],[-1.5,.9],[1.5,.9],[0,2.0],[-1.6,3.3],[1.6,3.3]]
};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;

export class FootballGame {
 private scene=new THREE.Scene(); private camera=new THREE.PerspectiveCamera(48,1,.1,100); private renderer:THREE.WebGLRenderer;
 private ball!:THREE.Mesh; private ballVel=new THREE.Vector3(); private ballSpin=new THREE.Vector3(); private players:Player[]=[]; private controlled!:Player; private keys=new Set<string>(); private running=true; private raf=0; private last=performance.now(); private elapsed=0; private matchSeconds=0; private half=1; private score=[0,0]; private difficulty:Difficulty; private formation:FormationName='4-3-3'; private goalCooldown=0; private eventText='KICK OFF'; private listeners=new Set<(s:any)=>void>(); private resizeObserver:ResizeObserver;
 private pitchW=105, pitchH=68, scale=.105; private goalZ=3.66;
 constructor(private host:HTMLElement,difficulty:Difficulty='Amateur',formation:FormationName='4-3-3'){this.difficulty=difficulty;this.formation=formation;this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;host.appendChild(this.renderer.domElement);this.buildWorld();this.spawnTeams();this.resetKickoff(0);this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();window.addEventListener('keydown',this.keyDown);window.addEventListener('keyup',this.keyUp);this.raf=requestAnimationFrame(this.loop);}
 onState(fn:(s:any)=>void){this.listeners.add(fn);fn(this.state());return()=>this.listeners.delete(fn)}
 private emit(){const s=this.state();this.listeners.forEach(f=>f(s));}
 private state(){const m=Math.floor(this.matchSeconds),min=String(Math.floor(m/60)).padStart(2,'0'),sec=String(m%60).padStart(2,'0');return{score:[...this.score],time:`${min}:${sec}`,half:this.half,player:this.controlled?.name??'',stamina:Math.round(this.controlled?.stamina??100),event:this.eventText,shots:this.shots,shotsOn:this.shotsOn,passes:this.passes,completed:this.completed,poss:[this.poss[0],this.poss[1]]};}
 private shots=[0,0];private shotsOn=[0,0];private passes=[0,0];private completed=[0,0];private poss=[50,50];
 private buildWorld(){this.scene.background=new THREE.Color(0x08120f);this.scene.add(new THREE.HemisphereLight(0xdff8ef,0x07100c,2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-15,25,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);this.scene.add(sun);
  const grass=new THREE.Mesh(new THREE.PlaneGeometry(11.025,7.14),new THREE.MeshStandardMaterial({color:0x17633d,roughness:1}));grass.rotation.x=-Math.PI/2;grass.receiveShadow=true;this.scene.add(grass);
  const lineMat=new THREE.LineBasicMaterial({color:0xffffff});const line=(pts:number[][])=>{const g=new THREE.BufferGeometry().setFromPoints(pts.map(p=>new THREE.Vector3(p[0]*this.scale,p[1]*this.scale,-.01)));this.scene.add(new THREE.Line(g,lineMat));};
  const W=5.5125,H=3.57;line([[-W,-H],[W,-H],[W,H],[-W,H],[-W,-H]]);line([[0,-H],[0,H]]);const c=new THREE.EllipseCurve(0,0,.87,.87,0,Math.PI*2);line(c.getPoints(48).map(p=>[p.x,p.y]));
  for(const sy of[-1,1]){line([[-W,sy*1.5],[-3.9,sy*1.5],[-3.9,sy*H*.55],[-W,sy*H*.55]]);line([[W,sy*1.5],[3.9,sy*1.5],[3.9,sy*H*.55],[W,sy*H*.55]]);}
  const goalMat=new THREE.MeshStandardMaterial({color:0xf4faf7,roughness:.4});for(const z of[-3.66,3.66]){for(const x of[-.8,.8]){const p=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,1.05),goalMat);p.position.set(z>0?5.55:-5.55,0,x);this.scene.add(p)}const bar=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,1.7),goalMat);bar.rotation.z=Math.PI/2;bar.position.set(z>0?5.55:-5.55,0,0);this.scene.add(bar)}
  const stands=new THREE.Mesh(new THREE.BoxGeometry(12,.6,9),new THREE.MeshStandardMaterial({color:0x18221f}));stands.position.y=-.3;this.scene.add(stands);this.camera.position.set(0,7.8,8.5);this.camera.lookAt(0,0,0);
  this.ball=new THREE.Mesh(new THREE.SphereGeometry(.13,16,10),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.35}));this.ball.castShadow=true;this.scene.add(this.ball);
 }
 private spawnTeams(){for(let team=0;team<2;team++){const formation=FORMATIONS[this.formation];const gk=this.makePlayer(team,0,team?'Keeper B':'Keeper A','GK',50);this.players.push(gk);formation.forEach((p,i)=>{const role=i<3?'DEF':i<6?'MID':'ATT';this.players.push(this.makePlayer(team,i+1,`Player ${team?'B':'A'}-${i+1}`,role,50+i%6*5));});}this.controlled=this.players.find(p=>p.team===0&&p.role==='ATT')!;this.controlled.hasBall=true;}
 private makePlayer(team:0|1,num:number,name:string,role:string,ovr:number){const s={pace:clamp(ovr+5,45,95),shooting:clamp(ovr+(role==='ATT'?12:0),45,95),passing:clamp(ovr+(role==='MID'?10:0),45,95),dribbling:clamp(ovr+(role==='ATT'?8:0),45,95),defending:clamp(ovr+(role==='DEF'?15:0),45,95),physical:clamp(ovr+3,45,95),stamina:clamp(ovr+5,45,99),reactions:clamp(ovr+4,45,99)};const group=new THREE.Group();const skin=new THREE.MeshStandardMaterial({color:0xc88767,roughness:.75}),shirt=new THREE.MeshStandardMaterial({color:team?0xd44747:0x39a9ff,roughness:.65}),shorts=new THREE.MeshStandardMaterial({color:team?0x6e1f2a:0x102d65,roughness:.7});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.11,.24,5,8),shirt);body.position.y=.34;body.castShadow=true;group.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.085,10,8),skin);head.position.y=.62;head.castShadow=true;group.add(head);for(const x of[-.055,.055]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.035,.25,4,6),shorts);leg.position.set(x,.08,0);leg.castShadow=true;group.add(leg)}for(const x of[-.16,.16]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.025,.22,4,6),shirt);arm.position.set(x,.36,0);arm.rotation.z=x>0?-.12:.12;group.add(arm)}const label=new THREE.Sprite(new THREE.SpriteMaterial({map:this.textTexture(`${num}`),transparent:true}));label.scale.set(.22,.11,1);label.position.set(0,.82,0);group.add(label);this.scene.add(group);return{id:num+(team?20:0),team,name,number:num,role,stats:s,pos:new THREE.Vector3(),vel:new THREE.Vector3(),mesh:group,hasBall:false,stamina:100,yellow:0,red:false,target:new THREE.Vector3()};}
 private textTexture(text:string){const c=document.createElement('canvas');c.width=64;c.height=32;const x=c.getContext('2d')!;x.fillStyle='white';x.font='bold 22px Arial';x.textAlign='center';x.fillText(text,32,23);return new THREE.CanvasTexture(c)}
 private resetKickoff(team:number){this.ball.position.set(0,.13,0);this.ballVel.set(0,0,0);this.players.forEach(p=>{const form=FORMATIONS[this.formation];if(p.number===0){p.pos.set(team?5.05:-5.05,0,0)}else{const q=form[p.number-1];const side=p.team===0?-1:1;p.pos.set(side*q[1]*this.scale,q[0]*this.scale,0)}});this.players.forEach(p=>{p.hasBall=false;p.mesh.position.copy(p.pos);p.vel.set(0,0,0)});const striker=this.players.find(p=>p.team===team&&p.role==='ATT')!;striker.hasBall=true;this.controlled=this.players.find(p=>p.team===0&&p.role==='ATT')!;this.eventText='KICK OFF';}
 private keyDown=(e:KeyboardEvent)=>{this.keys.add(e.key.toLowerCase());if([' ','j','k','l','i','o','p'].includes(e.key.toLowerCase()))e.preventDefault();};private keyUp=(e:KeyboardEvent)=>this.keys.delete(e.key.toLowerCase());
 private loop=(now:number)=>{const dt=clamp((now-this.last)/1000,0,.033);this.last=now;if(this.running)this.update(dt);this.render();this.raf=requestAnimationFrame(this.loop)};
 private update(dt:number){this.elapsed+=dt;this.goalCooldown=Math.max(0,this.goalCooldown-dt);if(this.matchSeconds<45*60){this.matchSeconds+=dt;if(this.matchSeconds>=45*60&&this.half===1){this.half=2;this.matchSeconds=45*60;this.eventText='HALF TIME';this.resetKickoff(1);}}else if(this.half===2&&this.matchSeconds>=90*60){this.running=false;this.eventText='FULL TIME';this.emit();return}
  if(this.keys.has(' '))this.switchPlayer();this.controlUser(dt);this.ai(dt);this.ballPhysics(dt);this.resolvePossession();this.updatePossession();this.cameraUpdate(dt);if(Math.floor(this.elapsed*4)%4===0)this.emit();}
 private switchCooldown=0;private switchPlayer(){if(this.switchCooldown>0)return;this.switchCooldown=.35;const candidates=this.players.filter(p=>p.team===0&&!p.red).sort((a,b)=>a.pos.distanceTo(this.ball.position)-b.pos.distanceTo(this.ball.position));if(candidates[0])this.controlled=candidates[0];}
 private controlUser(dt:number){this.switchCooldown=Math.max(0,this.switchCooldown-dt);const p=this.controlled;if(!p||p.red)return;const dir=new THREE.Vector3((this.keys.has('d')?1:0)-(this.keys.has('a')?1:0),0,(this.keys.has('s')?1:0)-(this.keys.has('w')?1:0));if(dir.lengthSq())dir.normalize();const sprint=this.keys.has('shift')&&p.stamina>1;const max=(p.stats.pace/100)*(sprint?2.15:1.35);const accel=8;const desired=dir.multiplyScalar(max);p.vel.lerp(desired,1-Math.exp(-accel*dt));p.pos.addScaledVector(p.vel,dt);p.stamina=clamp(p.stamina-(sprint?8:1)*dt,0,100);if(!sprint)p.stamina=clamp(p.stamina+3*dt,0,100);this.clampPitch(p.pos);p.mesh.position.copy(p.pos);if(p.hasBall)this.dribbleBall(p,dt);
  if(this.keys.has('j'))this.pass(p,false);if(this.keys.has('k'))this.pass(p,true);if(this.keys.has('l'))this.shoot(p,'normal');if(this.keys.has('p'))this.shoot(p,'chip');if(this.keys.has('i'))this.shoot(p,'cross');if(this.keys.has('o'))this.tackle(p);}
 private actionCooldown=0;private pass(p:Player,through:boolean){if(this.actionCooldown>0||!p.hasBall)return;this.actionCooldown=.22;const mates=this.players.filter(x=>x.team===p.team&&x!==p&&!x.red).sort((a,b)=>{const da=a.pos.distanceTo(p.pos),db=b.pos.distanceTo(p.pos);return through?Math.abs(a.pos.x-p.pos.x)-Math.abs(b.pos.x-p.pos.x):da-db});const r=mates[0];if(!r)return;const accuracy=p.stats.passing/100;const d=r.pos.clone().sub(p.pos);d.y=0;d.normalize();const err=(1-accuracy)*.35;d.z+=((Math.random()-.5)*err);d.normalize();this.ball.position.copy(p.pos).add(new THREE.Vector3(0,.16,0));this.ballVel.copy(d).multiplyScalar(through?3.9:3.1*(.65+accuracy*.35));this.ballVel.y=through?.25:.12;p.hasBall=false;this.passes[p.team]++;this.eventText=through?'THROUGH BALL':'PASS';}
 private shoot(p:Player,type:'normal'|'chip'|'cross'){if(this.actionCooldown>0||!p.hasBall)return;this.actionCooldown=.42;const target=new THREE.Vector3(5.55,p.pos.y,p.pos.z);const dir=target.sub(p.pos);dir.y=0;dir.normalize();const accuracy=p.stats.shooting/100;dir.z+=(Math.random()-.5)*(1-accuracy)*.5;dir.normalize();let power=type==='chip'?4.5:4.8*(.7+accuracy*.5);this.ball.position.copy(p.pos).add(new THREE.Vector3(0,.16,0));this.ballVel.copy(dir).multiplyScalar(power);this.ballVel.y=type==='chip'?2.1:1.0+accuracy*.45;this.ballSpin.set(0,(Math.random()-.5)*2,(Math.random()-.5)*2);p.hasBall=false;this.shots[p.team]++;this.eventText=type==='chip'?'CHIP SHOT':'SHOT';}
 private tackle(p:Player){if(this.actionCooldown>0)return;this.actionCooldown=.35;const opp=this.players.filter(x=>x.team!==p.team&&!x.red).sort((a,b)=>a.pos.distanceTo(p.pos)-b.pos.distanceTo(p.pos))[0];if(opp&&opp.pos.distanceTo(p.pos)<.42){if(Math.random()<p.stats.defending/120){opp.hasBall=false;this.ball.position.copy(opp.pos);this.ballVel.set((p.team? -1:1)*.8,0,(Math.random()-.5)*.8);this.eventText='TACKLE';}else{p.stamina=clamp(p.stamina-5,0,100);this.eventText='FOUL';if(Math.random()<.15)opp.yellow++;}}}
 private dribbleBall(p:Player,dt:number){const facing=p.vel.lengthSq()?p.vel.clone().normalize():new THREE.Vector3(p.team?1:-1,0,0);const touch=.20+(1-p.stats.dribbling/100)*.10;const desired=p.pos.clone().addScaledVector(facing,touch);desired.y=.13;this.ball.position.lerp(desired,1-Math.exp(-18*dt));this.ballVel.copy(p.vel);}
 private ai(dt:number){const aiTeam=this.players.filter(p=>p.team===1&&!p.red);for(const p of aiTeam){const target=this.tacticalTarget(p);const to=target.sub(p.pos);to.y=0;const d=to.length();if(d>.04){to.normalize();const speed=(p.stats.pace/100)*(1.0+(this.difficulty==='Legendary'?.28:0));p.vel.lerp(to.multiplyScalar(Math.min(1.7,speed)),1-Math.exp(-5*dt));}else p.vel.multiplyScalar(.8);p.pos.addScaledVector(p.vel,dt);this.clampPitch(p.pos);p.mesh.position.copy(p.pos);if(p.hasBall){if(p.pos.x<-.8&&p.role!=='DEF')this.aiShoot(p);else if(Math.random()<.015)this.aiPass(p);} }
  const human=this.players.filter(p=>p.team===0&&!p.red);for(const p of human){if(p===this.controlled)continue;const target=this.tacticalTarget(p);const to=target.sub(p.pos);to.y=0;if(to.length()>.08){to.normalize();p.vel.lerp(to.multiplyScalar(.8),1-Math.exp(-3*dt));p.pos.addScaledVector(p.vel,dt);this.clampPitch(p.pos);p.mesh.position.copy(p.pos);}}
 }
 private tacticalTarget(p:Player){if(p.hasBall)return this.ball.position.clone();const side=p.team===0?-1:1;const form=FORMATIONS[this.formation];if(p.number===0)return new THREE.Vector3(side*5.05,0,this.ball.position.z*.18);const q=form[p.number-1];let x=side*q[1]*this.scale,z=q[0]*this.scale;if(p.team===1)x=-x;const pressure=this.ball.position.distanceTo(new THREE.Vector3(x,0,z));if(pressure<1.2){x=lerp(x,this.ball.position.x,.35);z=lerp(z,this.ball.position.z,.35);}return new THREE.Vector3(x,z,0).setX(x).setY(0).setZ(z);}
 private aiShoot(p:Player){if(this.actionCooldown>0||!p.hasBall)return;const target=new THREE.Vector3(-5.55,0,clamp(p.pos.z+(Math.random()-.5)*1.2,-1.4,1.4));const d=target.sub(p.pos);d.normalize();this.ball.position.copy(p.pos);this.ballVel.copy(d).multiplyScalar(3.7+p.stats.shooting/55);this.ballVel.y=.8+p.stats.shooting/130;p.hasBall=false;this.shots[1]++;this.eventText='AI SHOT';}
 private aiPass(p:Player){const mates=this.players.filter(x=>x.team===p.team&&x!==p&&!x.red);const r=mates[Math.floor(Math.random()*mates.length)];if(!r)return;const d=r.pos.clone().sub(p.pos);d.y=0;d.normalize();this.ball.position.copy(p.pos);this.ballVel.copy(d).multiplyScalar(2.8);this.ballVel.y=.1;p.hasBall=false;this.passes[1]++;}
 private ballPhysics(dt:number){this.actionCooldown=Math.max(0,this.actionCooldown-dt);if(this.players.some(p=>p.hasBall)){this.ballVel.multiplyScalar(.85);return;}this.ballVel.y-=7.8*dt;this.ball.position.addScaledVector(this.ballVel,dt);this.ballVel.multiplyScalar(Math.pow(.992,dt*60));this.ball.rotation.x+=this.ballSpin.x*dt;this.ball.rotation.z+=this.ballSpin.z*dt;if(this.ball.position.y<.13){this.ball.position.y=.13;this.ballVel.y*=-.48;this.ballVel.x*=.96;this.ballVel.z*=.96;}if(Math.abs(this.ball.position.z)>3.57){this.ball.position.z=clamp(this.ball.position.z,-3.57,3.57);this.ballVel.z*=-.65;}if(Math.abs(this.ball.position.x)>5.55){if(this.ball.position.x>5.55&&Math.abs(this.ball.position.z)<.82){this.goal(0);return;}if(this.ball.position.x<-5.55&&Math.abs(this.ball.position.z)<.82){this.goal(1);return;}this.ball.position.x=clamp(this.ball.position.x,-5.55,5.55);this.ballVel.x*=-.65;}
 }
 private resolvePossession(){if(this.goalCooldown>0)return;let nearest:Player|undefined;let best=.28;for(const p of this.players){if(p.red)continue;const d=p.pos.distanceTo(this.ball.position);if(d<best){best=d;nearest=p;}}if(nearest&&this.ball.position.y<.34){const opponent=this.players.find(p=>p.hasBall);if(opponent&&opponent.team!==nearest.team&&Math.random()>.45)return;this.players.forEach(p=>p.hasBall=false);nearest.hasBall=true;this.ballVel.set(0,0,0);this.eventText=`${nearest.name} CONTROLS`;}}
 private updatePossession(){const a=this.players.filter(p=>p.team===0&&p.hasBall).length,b=this.players.filter(p=>p.team===1&&p.hasBall).length;if(a||b){this.poss[0]=lerp(this.poss[0],a?65:35,.015);this.poss[1]=100-this.poss[0];}}
 private goal(team:number){if(this.goalCooldown>0)return;this.score[team]++;this.shotsOn[team]++;this.goalCooldown=2;this.eventText=`GOAL — ${team===0?'BLUE':'RED'} TEAM`;this.players.forEach(p=>p.hasBall=false);setTimeout(()=>{if(this.running)this.resetKickoff(team===0?1:0)},1100);}
 private clampPitch(v:THREE.Vector3){v.x=clamp(v.x,-5.35,5.35);v.z=clamp(v.z,-3.35,3.35);v.y=0;}
 private cameraUpdate(dt:number){const target=this.controlled?.pos??this.ball.position;const desired=new THREE.Vector3(target.x*.42,6.8,6.7+target.z*.15);this.camera.position.lerp(desired,1-Math.exp(-4*dt));this.camera.lookAt(lerp(target.x,this.ball.position.x,.45),0,lerp(target.z,this.ball.position.z,.45));}
 private render(){const w=this.host.clientWidth,h=this.host.clientHeight;if(w&&h){this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);}this.renderer.render(this.scene,this.camera)}
 private resize(){this.render()}
 destroy(){this.running=false;cancelAnimationFrame(this.raf);this.resizeObserver.disconnect();window.removeEventListener('keydown',this.keyDown);window.removeEventListener('keyup',this.keyUp);this.renderer.dispose();this.scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose();const mat=m.material as THREE.Material|THREE.Material[];if(Array.isArray(mat))mat.forEach(x=>x.dispose());else mat?.dispose()});this.host.replaceChildren();}
}
